// Generated by ts-to-zod
import { z } from "zod";

export const correlatableSchema = z.object({
  correlationId: z.string(),
});

export const userProvidedTextSchema = z.string();

export const todoIdSchema = z.string();

export const userIdSchema = z.string();

export const todoCreatedRequestedEventPayloadSchema = correlatableSchema.extend({
  user: userIdSchema,
  title: userProvidedTextSchema,
  creationDate: z.string(),
});

export const todoCreatedEventPayloadSchema = correlatableSchema.extend({
  todoId: todoIdSchema,
  user: userIdSchema,
  title: userProvidedTextSchema,
  creationDate: z.string(),
});

export const todoRemoveRequestedPayloadSchema = correlatableSchema.extend({
  todoId: todoIdSchema,
});

export const todoRemovedPayloadSchema = correlatableSchema.extend({
  todoId: todoIdSchema,
});
